---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clip-deployment
  namespace: clip
spec:
  selector:
    matchLabels:
      app: clip
  template:
    metadata:
      labels:
        app: clip
    spec:
      serviceAccountName: clip-service-account
      containers:
      - name: clip
        image: registry.gitlab.com/willswire/cosmology/clip:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: cloudflare-credentials
                key: AUTH_KEY
          - name: ZONE_ID
            valueFrom:
              secretKeyRef:
                name: cloudflare-credentials
                key: ZONE_ID