build:
  image: $CI_REGISTRY_IMAGE/toolbox
  stage: build
  before_script:
    - mkdir -p $HOME/.kube
    - cat $CONFIG > $HOME/.kube/config
    - echo $REGISTRY1_CLI_SECRET | zarf tools registry login registry1.dso.mil --username $REGISTRY1_USERNAME --password-stdin
    - echo $CI_REGISTRY_PASSWORD | zarf tools registry login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - cd applications
    - sops -d -i secrets.yaml
    - zarf package create --skip-sbom --confirm --no-progress
    - zarf package deploy zarf-package-*.tar.zst --confirm --no-progress
