apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "endlessh.fullname" . }}
  labels:
    {{- include "endlessh.labels" . | nindent 4 }}
data:
    config: |
        # The port on which to listen for new SSH connections.
        Port {{ .Values.service.port }}

        # The endless banner is sent one line at a time. This is the delay
        # in milliseconds between individual lines.
        Delay {{ .Values.endlessh.delay }}

        # The length of each line is randomized. This controls the maximum
        # length of each line. Shorter lines may keep clients on for longer if
        # they give up after a certain number of bytes.
        MaxLineLength {{ .Values.endlessh.maxLineLength }}

        # Maximum number of connections to accept at a time. Connections beyond
        # this are not immediately rejected, but will wait in the queue.
        MaxClients {{ .Values.endlessh.maxClients }}

        # Set the detail level for the log.
        #   0 = Quiet
        #   1 = Standard, useful log messages
        #   2 = Very noisy debugging information
        LogLevel {{ .Values.endlessh.logLevel }}

        # Set the family of the listening socket
        #   0 = Use IPv4 Mapped IPv6 (Both v4 and v6, default)
        #   4 = Use IPv4 only
        #   6 = Use IPv6 only
        BindFamily {{ .Values.endlessh.bindFamily }}
