apiVersion: v1
kind: Service
metadata:
  name: {{ include "endlessh.fullname" . }}
  labels:
    {{- include "endlessh.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 2222
      targetPort: 2222
      protocol: TCP
      name: ssh
  selector:
    {{- include "endlessh.selectorLabels" . | nindent 4 }}
