package:
  name: clip
  version: 0.2.0
  epoch: 0
  description: Cloudflare-Istio Publisher
  copyright:
    - license: Apache-2.0
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - build-base
      - ca-certificates-bundle
      - go

pipeline:
  - uses: go/build
    with:
      output: clip
      packages: .

  - uses: strip