# Default values for endlessh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

endlessh:
  delay: 10000
  maxLineLength: 32
  maxClients: 4096
  logLevel: 1
  bindFamily: 4

image:
  repository: registry.gitlab.com/willswire/cosmology/endlessh
  pullPolicy: IfNotPresent
  tag: "1.0"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
